# Generated by Django 5.1.2 on 2025-02-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_productid_rating_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='grade',
        ),
    ]
